name = "NSFD"
uuid = "09ffc641-5453-42d0-a4b3-c4b7525e2ea1"
authors = ["Marian Domanski <mmdski@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"

[compat]
CairoMakie = "0.15.3"
julia = "1.6.7"
